Numpy Tutorials for Data Science CT

In [69]:
import numpy as np

In [70]:
myarr = np.array([3,6,32,7,31],np.int64)

In [71]:
myarr[0]

np.int64(3)

In [72]:
myarr.shape

(5,)

In [73]:
myarr.dtype

dtype('int64')

In [74]:
myarr[3]=55

In [75]:
myarr

array([ 3,  6, 32, 55, 31])

#Array Creation : Conversion from other python structures

In [76]:
listarray=np.array([[1,2,3],[5,8,5],[0,3,1]])

In [77]:
listarray

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [78]:
listarray.dtype

dtype('int64')

In [79]:
listarray.shape

(3, 3)

In [80]:
listarray.size

9

In [81]:
zeros=np.zeros((2,5))

In [82]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [83]:
zero1=np.zeros((5))

In [84]:
zero1.shape

(5,)

In [85]:
zero1

array([0., 0., 0., 0., 0.])

In [86]:
rng=np.arange(20)

In [87]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [88]:
lspcae=np.linspace(1,50,6)

In [89]:
lspcae

array([ 1. , 10.8, 20.6, 30.4, 40.2, 50. ])

In [90]:
emp=np.empty((2,3))

In [91]:
emp

array([[ 1. , 10.8, 20.6],
       [30.4, 40.2, 50. ]])

In [92]:
emp_like=np.empty_like(lspcae)

In [93]:
emp_like

array([ 1. , 10.8, 20.6, 30.4, 40.2, 50. ])

In [94]:
ide = np.identity(45)

In [95]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [96]:
ide.shape

(45, 45)

In [97]:
arr = np.arange(99)

In [98]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [99]:
arr = arr.reshape(3,33)

In [100]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [101]:
inpt=[2,3,5,6]

In [102]:
n1=np.geomspace(1,1000,4)

In [103]:
n1

array([   1.,   10.,  100., 1000.])

In [104]:
n2=n1.copy()

In [105]:
n2

array([   1.,   10.,  100., 1000.])

In [106]:
arr. shape

(3, 33)

In [107]:
ones = np.ones((3,6))

In [108]:
ones

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [109]:
newarr=np.array([[3,3],[4,5]])

In [110]:
newarr

array([[3, 3],
       [4, 5]])

In [111]:
newarr.ravel()

array([3, 3, 4, 5])

In [112]:
ey=np.eye(3)

In [113]:
ey

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [114]:
ident=np.identity(3)

In [115]:
ident

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [116]:
ny=np.random.rand(3,5)

In [117]:
ny

array([[0.53061587, 0.292952  , 0.22339006, 0.66844674, 0.33357394],
       [0.22781829, 0.9805976 , 0.94732984, 0.2731801 , 0.797804  ],
       [0.44496552, 0.98489395, 0.38907368, 0.65304328, 0.17314105]])

In [118]:
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

In [119]:
d=np.diag(a)

In [120]:
d

array([1, 5, 9])

In [121]:
np.triu([[1,2,3],
              [4,5,6],
              [7,8,9]])

array([[1, 2, 3],
       [0, 5, 6],
       [0, 0, 9]])

In [122]:
np.tril([[1,2,3],
              [4,5,6],
              [7,8,9]])

array([[1, 0, 0],
       [4, 5, 0],
       [7, 8, 9]])

In [123]:
np.logspace(1,5,3)

array([1.e+01, 1.e+03, 1.e+05])

In [124]:
c=np.array([1, 1, 1, 1, 1], ndmin=10)

In [125]:
c

array([[[[[[[[[[1, 1, 1, 1, 1]]]]]]]]]])

In [126]:
e = np.array([1,2,3,5,6,8,24,6,12])

In [127]:
e

array([ 1,  2,  3,  5,  6,  8, 24,  6, 12])

In [128]:
e[3]

np.int64(5)

In [129]:
e[0:4]

array([1, 2, 3, 5])

In [130]:
e[0:4:2]

array([1, 3])

In [131]:
e[::2]

array([ 1,  3,  6, 24, 12])

In [132]:
e[-1]

np.int64(12)

In [133]:
f = np.array([[1,2,3,5,6,8,24,6,12],[31,42,85,54,5,77,7,21,2]])

In [134]:
f

array([[ 1,  2,  3,  5,  6,  8, 24,  6, 12],
       [31, 42, 85, 54,  5, 77,  7, 21,  2]])

In [135]:
for x in f:
  for y in x:
    print(y)

1
2
3
5
6
8
24
6
12
31
42
85
54
5
77
7
21
2


In [136]:
for x in np.nditer(f):
  print(x)

1
2
3
5
6
8
24
6
12
31
42
85
54
5
77
7
21
2
