In [ ]:
import numpy as np

In [ ]:
firstarr = np.arange(11)

In [ ]:
firstarr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
onearr = np.ones((3,3))

In [ ]:
onearr

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
fillarr=np.full((3,3),5)

In [ ]:
fillarr

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [ ]:
lspace = np.linspace(10,20,5)

In [ ]:
lspace

array([10. , 12.5, 15. , 17.5, 20. ])

In [ ]:
onearr.shape

(3, 3)

In [ ]:
onearr.dtype

dtype('float64')

In [ ]:
randarr = np.random.rand(4,5)

In [ ]:
randarr

array([[0.35493393, 0.16829634, 0.92018408, 0.59883465, 0.57981389],
       [0.39494589, 0.32771238, 0.0430908 , 0.31921867, 0.72982491],
       [0.00559179, 0.67900105, 0.73684495, 0.92747152, 0.0403842 ],
       [0.96419367, 0.88261815, 0.7725061 , 0.76558535, 0.42343836]])

In [ ]:
randarr.size

20

In [ ]:
newarr = np.array([1,2,3,4,5,6])

In [ ]:
newarr

array([1, 2, 3, 4, 5, 6])

In [ ]:
newarr.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr1=np.array([1,2,3])

In [ ]:
arr2=np.array([4,5,6])

In [ ]:
arr1
arr2

array([4, 5, 6])

In [ ]:
arr3 = np.concatenate((arr1, arr2))

In [ ]:
arr3

array([1, 2, 3, 4, 5, 6])

In [ ]:
np.split(arr3,3)

[array([1, 2]), array([3, 4]), array([5, 6])]

In [ ]:
searchval = np.array([3,5,1,9,5])

In [ ]:
searchval

array([3, 5, 1, 9, 5])

In [ ]:
positions = np.where(searchval==5)

In [ ]:
positions

(array([1, 4]),)

In [ ]:
slicingarr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
slicingarr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
slicingarr[1]

array([4, 5, 6])

In [ ]:
slicingarr[:, 1:]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [ ]:
slicingarr.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
iteratingArray = np.array([10,20,30])

In [ ]:
arr2d = iteratingArray[:,np.newaxis]

In [ ]:
arr2d

array([[10],
       [20],
       [30]])

In [ ]:
for x in iteratingArray:
  print(x)

10
20
30


In [ ]:
copyarr = iteratingArray.copy()

In [ ]:
copyarr[0]=100

In [ ]:
copyarr

array([100,  20,  30])

In [ ]:
iteratingArray

array([10, 20, 30])

In [ ]:
ide = np.identity(4)

In [ ]:
ide

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
ey=np.eye(3)

In [ ]:
ey

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
randarr1=np.random.rand(5)

In [ ]:
randarr1

array([0.51329543, 0.95584924, 0.94202779, 0.11038023, 0.69827872])

**Data Analysis for Weather Monitoring**

In [ ]:
temp = np.random.randint(15,41,size=(5,7))

In [ ]:
temp

array([[35, 40, 34, 17, 22, 28, 36],
       [28, 15, 32, 34, 40, 38, 29],
       [34, 34, 15, 39, 15, 33, 20],
       [29, 34, 22, 17, 26, 21, 16],
       [30, 36, 35, 35, 19, 31, 33]])

In [ ]:

for x in temp:
  sum = 0
  for y in x:
    sum+=y
  avg = sum/7
  print(avg)


30.285714285714285
30.857142857142858
27.142857142857142
23.571428571428573
31.285714285714285


In [ ]:
for x in temp:
  max = 0
  for y in x:
    if y>max:
      max=y
  print(max)

40
40
39
34
36


In [ ]:
temp.sort()

In [ ]:
temp

array([[17, 22, 28, 34, 35, 36, 40],
       [15, 28, 29, 32, 34, 38, 40],
       [15, 15, 20, 33, 34, 34, 39],
       [16, 17, 21, 22, 26, 29, 34],
       [19, 30, 31, 33, 35, 35, 36]])

In [ ]:
temp.ravel()

array([17, 22, 28, 34, 35, 36, 40, 15, 28, 29, 32, 34, 38, 40, 15, 15, 20,
       33, 34, 34, 39, 16, 17, 21, 22, 26, 29, 34, 19, 30, 31, 33, 35, 35,
       36])

**Ecommerce Sales Data**

In [ ]:
sales = np.random.randint(50,201,size=(3,7))

In [ ]:
sales

array([[ 95, 113, 152, 157, 171, 136, 106],
       [ 87, 158,  69, 132, 188, 152, 190],
       [ 92,  63, 123, 160, 120,  91, 142]])

In [ ]:
for x in sales:
  sum = 0
  for y in x:
    sum+=y
  print(sum)

930
976
791


In [ ]:
for x in sales:
    total = 0
    for y in x:
        total += y
    print(total)

930
976
791


In [ ]:
new_sales = sales.copy()
new_sales[new_sales > 150] = 150
print(new_sales)

[[ 95 113 150 150 150 136 106]
 [ 87 150  69 132 150 150 150]
 [ 92  63 123 150 120  91 142]]
